name: Scheduled Update of Formulae
on:
    workflow_dispatch:
    schedule:
        - cron: "00 18 * * *"

jobs:
    update:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out code
              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

            - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
              with:
                  aqua_version: v2.55.0

            - name: Update formulae
              run: |
                  make update
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Commit and push
              uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
              with:
                  add: "Formula/*.rb"
